languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "Piyush Bhandari"

[params]
  dateFormat = "2 January 2006"

[params.author]
  name = "Piyush Bhandari"
  headline = "DevOps & SRE"
  bio = "I build highly available infrastructure."
  links = [
    { github = "https://github.com/piyushbhandaricode" }
  ]