colorScheme = "congo"
defaultAppearance = "light"
autoSwitchAppearance = true
defaultThemeColor = "#FFFFFF"

[header]
  layout = "basic"
  showTitle = true

[footer]
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = false
  showScrollToTop = true

[homepage]
  layout = "profile"

[article]
  showDate = true
  showAuthor = true
  showReadingTime = true